# Generated by Django 3.0.1 on 2020-08-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200805_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='type',
            field=models.CharField(choices=[('Alien Monolith', 'Alien Monolith'), ('Ancient Ruin', 'Ancient Ruin'), ('Space Anomaly', 'Space Anomaly'), ('Fauna', 'Fauna'), ('Flora', 'Flora'), ('Landscape', 'Landscape'), ('Miscellaneous', 'Miscellaneous')], max_length=30),
        ),
    ]
