# Generated by Django 3.0.1 on 2019-12-25 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0004_auto_20191224_1123'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('fauna_desc', models.CharField(blank=True, max_length=20)),
                ('fauna_hostility_desc', models.CharField(blank=True, max_length=50)),
                ('fauna_hostility_level', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('U', 'Unknown')], default='H', max_length=1)),
                ('flora_desc', models.CharField(blank=True, max_length=20)),
                ('has_base', models.BooleanField(default=False)),
                ('is_exotic', models.BooleanField(default=False)),
                ('is_weather_extreme', models.BooleanField(default=False)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('portal_address', models.CharField(blank=True, max_length=200)),
                ('resources_notes', models.TextField(blank=True)),
                ('sentinel_desc', models.CharField(blank=True, max_length=20)),
                ('sentinel_hostility_desc', models.CharField(blank=True, max_length=50)),
                ('sentinel_hostility_level', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('U', 'Unknown')], default='H', max_length=1)),
                ('type', models.CharField(choices=[('PLANET', 'Planet'), ('MOON', 'Moon')], default='PLANET', max_length=6)),
                ('weather_desc', models.CharField(blank=True, max_length=50)),
                ('weather_hazard_type', models.CharField(blank=True, choices=[('N', 'None'), ('H', 'Heat'), ('C', 'Cold'), ('T', 'Toxic'), ('R', 'Radiation'), ('U', 'Unknown')], max_length=1)),
                ('weather_notes', models.CharField(blank=True, max_length=50)),
                ('weather_rating', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('U', 'Unknown')], default='U', max_length=1)),
                ('resource_1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_1', to='reference.Resource')),
                ('resource_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_2', to='reference.Resource')),
                ('resource_3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_3', to='reference.Resource')),
                ('resource_4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_4', to='reference.Resource')),
                ('resource_5', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_5', to='reference.Resource')),
                ('resource_6', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_6', to='reference.Resource')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='systems.System')),
            ],
        ),
    ]
