# Generated by Django 3.0.1 on 2019-12-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='fauna_hostility_level',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='world',
            name='sentinel_hostility_level',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='world',
            name='weather_hazard_type',
            field=models.CharField(choices=[('N', 'None'), ('H', 'Heat'), ('C', 'Cold'), ('T', 'Toxic'), ('R', 'Radiation'), ('U', 'Unknown')], default='U', max_length=1),
        ),
    ]
