# Generated by Django 3.0.1 on 2019-12-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0003_auto_20191225_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='photo_marquee',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
