# Generated by Django 3.0.1 on 2020-01-02 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0006_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
    ]
