# Generated by Django 3.0.1 on 2020-01-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0007_delete_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='world',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='world',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='world',
            name='portal_address',
            field=models.CharField(blank=True, help_text='Hex code from https://nmsportals.github.io/', max_length=200),
        ),
    ]
