# Generated by Django 3.0.1 on 2020-05-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0008_auto_20200109_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='weather_hazard_type',
            field=models.CharField(choices=[('N', 'None'), ('H', 'Heat'), ('C', 'Cold'), ('T', 'Toxic'), ('R', 'Radiation'), ('U', 'Unknown'), ('S', 'Hot Rain')], default='U', max_length=1),
        ),
    ]
