# Generated by Django 3.1 on 2020-09-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0011_world_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='fauna_discovered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='fauna_maximum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
