# Generated by Django 3.1.7 on 2021-03-21 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_auto_20210321_1321'),
        ('worlds', '0012_auto_20200916_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='resources_notes',
            field=models.TextField(blank=True, help_text="Additional notes, eg. Ancient Bones, Tech Modules, resource occurrence frequency. Use the pipe '|' character to list multiple items."),
        ),
        migrations.CreateModel(
            name='Fauna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Additional notes', max_length=200, null=True)),
                ('is_hostile', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='From Discovery Data', max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('bait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reference.faunabait')),
                ('flesh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flesh_ingredient', to='reference.ingredient')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_ingredient', to='reference.ingredient')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='worlds.world')),
            ],
        ),
    ]
