# Generated by Django 3.1.7 on 2021-06-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0013_auto_20210321_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fauna',
        ),
    ]
