# Generated by Django 3.1.7 on 2021-06-02 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0014_delete_fauna'),
        ('reference', '0008_auto_20210525_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fauna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Additional notes', max_length=200, null=True)),
                ('is_hostile', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='From Discovery Data', max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('bait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reference.faunabait')),
                ('flesh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flesh_ingredient', to='reference.ingredient')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_ingredient', to='reference.ingredient')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='worlds.world')),
            ],
        ),
    ]
