# Generated by Django 3.0.1 on 2019-12-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_resource'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='economylevel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_level_name'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_resource_name'),
        ),
    ]
