# Generated by Django 3.0.1 on 2019-12-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_auto_20191224_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economylevel',
            name='level',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('U', 'U'), ('X', 'X')], default='U', max_length=1),
        ),
    ]
