# Generated by Django 3.1.7 on 2021-05-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_auto_20210321_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='type',
            field=models.CharField(choices=[('Norm', 'Norm'), ('Lush', 'Lush'), ('Harsh', 'Harsh'), ('Empty', 'Empty')], default='Norm', max_length=5),
        ),
    ]
