# Generated by Django 3.0.1 on 2019-12-25 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bases', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worlds.World'),
        ),
    ]
