# Generated by Django 3.0.1 on 2020-01-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0007_delete_base'),
        ('bases', '0002_base_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='world',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='worlds.World'),
        ),
    ]
