# Generated by Django 3.0.1 on 2020-06-11 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_auto_20200129_1607'),
        ('bases', '0006_auto_20200508_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='galaxy',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reference.Galaxy'),
        ),
    ]
