# Generated by Django 3.1 on 2020-09-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='platform',
            field=models.CharField(blank=True, choices=[('XBox', 'XBox'), ('Steam', 'Steam'), ('PlayStation', 'PlayStation'), ('Windows', 'Windows')], max_length=20, null=True),
        ),
    ]
