# Generated by Django 3.0.1 on 2019-12-25 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0004_auto_20191224_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('comments', models.TextField(blank=True)),
                ('conflict_level', models.CharField(blank=True, max_length=20)),
                ('economy_desc', models.CharField(blank=True, max_length=30)),
                ('gc_dist', models.IntegerField(blank=True)),
                ('num_moons', models.IntegerField(blank=True)),
                ('num_planets', models.IntegerField(blank=True)),
                ('portal_address', models.CharField(blank=True, max_length=200)),
                ('race', models.CharField(choices=[('Gek', 'Gek'), ('Korvax', 'Korvax'), ('Vykeen', 'Vykeen')], max_length=6)),
                ('space_station', models.CharField(blank=True, choices=[('Y', 'Present'), ('N', 'None'), ('A', 'Abandoned')], max_length=1)),
                ('star_classification', models.CharField(blank=True, max_length=5)),
                ('star_colour', models.CharField(blank=True, max_length=6)),
                ('economy_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.EconomyLevel')),
                ('near_system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='systems.System')),
            ],
        ),
    ]
