# Generated by Django 3.0.1 on 2019-12-25 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='gc_dist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='near_system',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systems.System'),
        ),
    ]
