# Generated by Django 3.0.1 on 2019-12-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20191225_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='num_moons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='num_planets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
