# Generated by Django 3.0.1 on 2019-12-25 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20191225_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='near_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systems.System'),
        ),
    ]
