# Generated by Django 3.0.1 on 2019-12-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_auto_20191225_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
