# Generated by Django 3.0.1 on 2019-12-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_system_photo_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
