# Generated by Django 3.0.1 on 2019-12-27 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_auto_20191226_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='discovered_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
