# Generated by Django 3.0.1 on 2019-12-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_system_discovered_by_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='teleportable',
            field=models.BooleanField(default=True),
        ),
    ]
