# Generated by Django 3.0.2 on 2020-01-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_auto_20200129_1607'),
        ('systems', '0011_system_teleportable'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='galaxy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reference.Galaxy'),
        ),
    ]
