# Generated by Django 3.0.1 on 2020-01-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_auto_20200129_1607'),
        ('systems', '0012_system_galaxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='galaxy',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reference.Galaxy'),
        ),
    ]
