# Generated by Django 3.0.1 on 2020-06-04 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_auto_20200507_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='black_hole',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='system',
            name='black_hole_dest_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='black_hole_dest_system_link', to='systems.System'),
        ),
        migrations.AddField(
            model_name='system',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
