# Generated by Django 3.0.1 on 2020-06-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0016_auto_20200604_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='near_system_dist',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
