# Generated by Django 3.1 on 2020-09-08 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('systems', '0018_auto_20200801_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='game_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.gamesession'),
        ),
    ]
