# Generated by Django 3.1 on 2020-09-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0019_system_game_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='star_count',
            field=models.IntegerField(default=1),
        ),
    ]
