# Generated by Django 3.1.7 on 2021-06-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0020_system_star_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='portal_address',
            field=models.CharField(blank=True, help_text='Hex code from https://nmsportals.github.io/', max_length=200),
        ),
    ]
