# Generated by Django 3.1.7 on 2021-06-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0021_auto_20210619_0838'),
        ('systems', '0021_auto_20210602_1930'),
    ]

    operations = [
    ]
